-- HandyNotes_ForeverInstances - WoW Forever only
-- Data source: user-provided WoWForeverInstances.lua
local addonName, ns = ...

-- WoWForeverInstances.lua
-- Consolidated WoW Forever dungeon / raid database.
--
-- Primary sources:
--   https://www.warcrafttavern.com/forever/guides/dungeons/
--   https://wowhandbook.com/zones/dungeons/
--   https://www.warcrafttavern.com/forever/guides/raids/
--   https://wowhandbook.com/zones/raids/
--
-- Coordinates are zone-map percentages (0..100), NOT normalized 0..1.
-- Use DB.GetNormalizedCoordinates() for C_Map / normalized consumers.
--
-- Data policy:
--   * Level ranges: current WoW Forever table from Warcraft Tavern.
--   * Classic entrance coords: WoW Handbook where consistent.
--   * Conflicting coordinates were cross-checked instead of copied blindly.
--   * Unknown/TBA Forever entrance coordinates remain nil.
--   * Unified descriptions: concise paraphrases synthesized from the checked Forever dungeon/raid resources;
--     the UI does not split descriptions by source.
--   * Returning Classic instances are marked as available in Forever without duplicating map nodes.
--   * Unnamed roadmap raids are intentionally not added as map records until a name/location is published.

local DB = {
    version = 2,
    coordinateUnit = "percent",

    Dungeons = {
        Classic = {
            ragefire_chasm = {
                name = "Ragefire Chasm",
                levelMin = 13,
                levelMax = 18,
                minEntryLevel = 8,
                zone = "Orgrimmar",
                x = 53.0,
                y = 48.9,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "Volcanic caverns beneath Orgrimmar where Burning Blade warlocks and demonic forces gather; a compact early Horde dungeon.",
                descriptionUk = "Вулканічні печери під Орґріммаром, де збираються чаклуни Палаючого Клинка та демонічні сили; компактне раннє підземелля Орди.",
                bossCount = 4,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            deadmines = {
                name = "The Deadmines",
                aliases = { "Deadmines" },
                levelMin = 15,
                levelMax = 22,
                minEntryLevel = 10,
                zone = "Westfall",
                x = 38.2,
                y = 77.5,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "The Defias Brotherhood's hidden complex beneath Westfall, leading through old mines to a pirate ship and Edwin VanCleef.",
                descriptionUk = "Прихований комплекс Братства Дефіас під Західним Краєм: від старих шахт до піратського корабля та Едвіна ван Кліфа.",
                bossCount = 7,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            wailing_caverns = {
                name = "Wailing Caverns",
                levelMin = 17,
                levelMax = 24,
                minEntryLevel = 10,
                zone = "The Barrens",
                x = 46.0,
                y = 36.3,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "A winding cave network in the Barrens where Naralex's dream has twisted druids, beasts, and the caverns around them.",
                descriptionUk = "Звивиста мережа печер у Степах, де сон Наралекса спотворив друїдів, звірів і самі печери.",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            shadowfang_keep = {
                name = "Shadowfang Keep",
                levelMin = 20,
                levelMax = 26,
                minEntryLevel = 10,
                zone = "Silverpine Forest",
                x = 44.7,
                y = 67.8,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "A gothic fortress above Pyrewood Village, haunted by cursed worgen and ruled by Archmage Arugal.",
                descriptionUk = "Готична фортеця над Пайрвудом, населена проклятими ворґенами та підвладна архімагу Аругалу.",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            blackfathom_deeps = {
                name = "Blackfathom Deeps",
                aliases = { "BFD" },
                levelMin = 22,
                levelMax = 28,
                minEntryLevel = 10,
                zone = "Ashenvale",
                x = 14.5,
                y = 14.6,
                players = 5,
                maxPlayers = 10,
                coordStatus = "conflict_resolved",
                coordSource = "warcrafttavern",
                note = "WoWHandbook currently places this in Darkshore; Warcraft Tavern and Classic references place the entrance at The Zoram Strand in Ashenvale.",
                description = "Sunken night elf ruins occupied by Twilight's Hammer cultists, satyrs, and the hydra Aku'mai.",
                descriptionUk = "Затоплені руїни нічних ельфів, зайняті культистами Сутінкового Молота, сатирами та гідрою Аку'май.",
                bossCount = 7,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            the_stockade = {
                name = "The Stockade",
                aliases = { "Stockade", "The Stockades" },
                levelMin = 25,
                levelMax = 29,
                minEntryLevel = 15,
                zone = "Stormwind City",
                x = 50.4,
                y = 66.2,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "Stormwind's fortified prison has fallen into a violent inmate uprising beneath the city.",
                descriptionUk = "Укріплена в'язниця Штормграда під містом охоплена жорстоким повстанням ув'язнених.",
                bossCount = 5,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            gnomeregan = {
                name = "Gnomeregan",
                levelMin = 29,
                levelMax = 38,
                minEntryLevel = 15,
                zone = "Dun Morogh",
                x = 24.0,
                y = 40.0,
                players = 5,
                maxPlayers = 10,
                coordStatus = "cross_checked",
                coordSource = "warcrafttavern",
                note = "Warcraft Tavern entrance coordinate; WoWHandbook uses a different point in the Gnomeregan exterior complex.",
                description = "The irradiated ruins of the gnomish capital, packed with malfunctioning machinery, troggs, and renegade forces.",
                descriptionUk = "Опромінені руїни гномської столиці, заповнені несправними механізмами, трогами та силами заколотників.",
                bossCount = 5,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            razorfen_kraul = {
                name = "Razorfen Kraul",
                aliases = { "RFK" },
                levelMin = 29,
                levelMax = 38,
                minEntryLevel = 15,
                zone = "The Barrens",
                x = 42.3,
                y = 89.9,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "A massive thorn maze grown from Agamaggan's legacy and controlled by quilboar under Charlga Razorflank.",
                descriptionUk = "Величезний колючий лабіринт, породжений спадщиною Агамаггана й контрольований квілборами під проводом Чарлґи Бритвобокої.",
                bossCount = 6,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            scarlet_monastery = {
                name = "The Scarlet Monastery",
                aliases = { "Scarlet Monastery", "SM" },
                levelMin = 30,
                levelMax = 46,
                minEntryLevel = 20,
                zone = "Tirisfal Glades",
                x = 85.1,
                y = 31.4,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                wings = {
                    graveyard = {
                        name = "Graveyard",
                        fullName = "The Scarlet Monastery - Graveyard",
                        levelMin = 30,
                        levelMax = 38,
                        minEntryLevel = 20,
                        players = 5,
                        maxPlayers = 10,
                    },
                    library = {
                        name = "Library",
                        fullName = "The Scarlet Monastery - Library",
                        levelMin = 33,
                        levelMax = 41,
                        minEntryLevel = 20,
                        players = 5,
                        maxPlayers = 10,
                    },
                    armory = {
                        name = "Armory",
                        fullName = "The Scarlet Monastery - Armory",
                        levelMin = 36,
                        levelMax = 44,
                        minEntryLevel = 20,
                        players = 5,
                        maxPlayers = 10,
                    },
                    cathedral = {
                        name = "Cathedral",
                        fullName = "The Scarlet Monastery - Cathedral",
                        levelMin = 38,
                        levelMax = 46,
                        minEntryLevel = 20,
                        players = 5,
                        maxPlayers = 10,
                    },
                },
                description = "The Scarlet Crusade's stronghold in Tirisfal, divided into Graveyard, Library, Armory, and Cathedral wings.",
                descriptionUk = "Оплот Багряного Походу в Тірісфалі, поділений на крила Цвинтаря, Бібліотеки, Збройової та Собору.",
                bossCount = 7,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            uldaman = {
                name = "Uldaman",
                levelMin = 36,
                levelMax = 45,
                minEntryLevel = 30,
                zone = "Badlands",
                x = 44.2,
                y = 12.2,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "An ancient Titan vault beneath the Badlands containing records of dwarven origins and the guardian Archaedas.",
                descriptionUk = "Стародавнє сховище титанів під Безплідними землями, де зберігаються таємниці походження дворфів і чатують охоронці на чолі з Аркедасом.",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            razorfen_downs = {
                name = "Razorfen Downs",
                aliases = { "RFD" },
                levelMin = 37,
                levelMax = 46,
                minEntryLevel = 25,
                zone = "The Barrens",
                x = 50.9,
                y = 92.9,
                players = 5,
                maxPlayers = 10,
                coordStatus = "cross_checked",
                coordSource = "wowhandbook",
                note = "WoWHandbook's ~50.9,92.9 agrees with Classic references for the actual instance entrance; some guides use an earlier approach point around 43,95.",
                description = "Quilboar ancestral catacombs corrupted by the Scourge and the lich Amnennar the Coldbringer.",
                descriptionUk = "Родові катакомби квілборів, осквернені Плеттю та лічем Амненнаром Холодоносцем.",
                bossCount = 6,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            zulfarrak = {
                name = "Zul'Farrak",
                aliases = { "ZF" },
                levelMin = 40,
                levelMax = 47,
                minEntryLevel = 35,
                zone = "Tanaris",
                x = 38.7,
                y = 19.9,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "The open-air Sandfury troll city in Tanaris, known for its pyramid battle and the hydra Gahz'rilla.",
                descriptionUk = "Відкрите місто тролів Піщаної Люті в Танарісі, відоме битвою біля піраміди та гідрою Газ'ріллою.",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            maraudon = {
                name = "Maraudon",
                levelMin = 45,
                levelMax = 51,
                minEntryLevel = 30,
                zone = "Desolace",
                x = 29.3,
                y = 62.5,
                players = 5,
                maxPlayers = 10,
                coordStatus = "cross_checked",
                coordSource = "wowhandbook",
                approach = {
                    x = 38.0,
                    y = 58.0,
                    label = "Valley of Spears / exterior approach",
                    source = "warcrafttavern",
                },
                description = "A vast centaur necropolis beneath Desolace where corrupted caverns descend toward Princess Theradras.",
                descriptionUk = "Величезний некрополь кентаврів під Спустошенням, де осквернені печери ведуть до принцеси Терадрас.",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            temple_of_atal_hakkar = {
                name = "The Temple of Atal'Hakkar",
                aliases = { "Temple of Atal'Hakkar", "Sunken Temple", "ST" },
                levelMin = 50,
                levelMax = 55,
                minEntryLevel = 35,
                zone = "Swamp of Sorrows",
                x = 69.0,
                y = 54.0,
                players = 5,
                maxPlayers = 10,
                coordStatus = "conflict_resolved",
                coordSource = "cross_check",
                note = "WoWHandbook currently lists 77.3,35.9. Classic entrance references and the actual temple location place the exterior entrance around 69,54.",
                description = "A sunken Atal'ai pyramid where Hakkar's cult operates among undead trolls and corrupted green dragons.",
                descriptionUk = "Затоплена піраміда Атал'ай, де культ Гаккара діє серед неживих тролів і спотворених зелених драконів.",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            blackrock_depths = {
                name = "Blackrock Depths",
                aliases = { "BRD" },
                levelMin = 52,
                levelMax = 60,
                minEntryLevel = 40,
                location = "Blackrock Mountain",
                zone = "Searing Gorge",
                x = 27.1,
                y = 72.5,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "The sprawling Dark Iron capital inside Blackrock Mountain, stretching from prisons and factories to Emperor Thaurissan's throne.",
                descriptionUk = "Величезна столиця дворфів Чорного Заліза всередині Чорної гори — від в'язниць і цехів до трону імператора Тауріссана.",
                bossCount = 21,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            blackrock_spire = {
                name = "Blackrock Spire",
                aliases = { "BRS" },
                levelMin = 57,
                levelMax = 60,
                minEntryLevel = 45,
                location = "Blackrock Mountain",
                zone = "Burning Steppes",
                x = 33.0,
                y = 25.2,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                wings = {
                    lower = {
                        name = "Lower Blackrock Spire",
                        aliases = { "LBRS" },
                        levelMin = 57,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 5,
                        maxPlayers = 10,
                    },
                    upper = {
                        name = "Upper Blackrock Spire",
                        aliases = { "UBRS" },
                        levelMin = 60,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 10,
                        maxPlayers = 10,
                    },
                },
                description = "A volcanic fortress above Blackrock Mountain split between Lower and Upper Spire, occupied by the Dark Horde and dragonkin.",
                descriptionUk = "Вулканічна фортеця над Чорною горою, поділена на Нижній і Верхній Шпиль та зайнята Темною Ордою й драконідами.",
                bossCount = 14,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            dire_maul = {
                name = "Dire Maul",
                aliases = { "DM" },
                levelMin = 58,
                levelMax = 60,
                minEntryLevel = 45,
                zone = "Feralas",
                x = 62.0,
                y = 33.3,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                wings = {
                    east = {
                        name = "Dire Maul East",
                        aliases = { "DME" },
                        levelMin = 58,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 5,
                        maxPlayers = 5,
                    },
                    west = {
                        name = "Dire Maul West",
                        aliases = { "DMW" },
                        levelMin = 60,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 5,
                        maxPlayers = 5,
                    },
                    north = {
                        name = "Dire Maul North",
                        aliases = { "DMN" },
                        levelMin = 60,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 5,
                        maxPlayers = 5,
                    },
                },
                description = "The ruined Highborne city of Eldre'Thalas, divided into three wings filled with demons, ogres, and ancient magic.",
                descriptionUk = "Руїни високородного міста Ельдре'Талас, поділені на три крила з демонами, ограми та стародавньою магією.",
                bossCount = 19,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            stratholme = {
                name = "Stratholme",
                levelMin = 58,
                levelMax = 60,
                minEntryLevel = 45,
                zone = "Eastern Plaguelands",
                x = 26.1,
                y = 10.4,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                wings = {
                    living = {
                        name = "Stratholme - Living",
                        aliases = { "Stratholme: Live", "Strat Live" },
                        levelMin = 58,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 5,
                        maxPlayers = 5,
                    },
                    undead = {
                        name = "Stratholme - Undead",
                        aliases = { "Stratholme: Dead", "Strat UD" },
                        levelMin = 58,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 5,
                        maxPlayers = 5,
                    },
                },
                description = "The burning remains of Stratholme, split between living Scarlet forces and Scourge-held undead districts.",
                descriptionUk = "Палаючі руїни Стратгольма, поділені між живими силами Багряного Походу та кварталами нежиті під контролем Плеті.",
                bossCount = 19,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            scholomance = {
                name = "Scholomance",
                aliases = { "Scholo" },
                levelMin = 58,
                levelMax = 60,
                minEntryLevel = 45,
                zone = "Western Plaguelands",
                x = 69.7,
                y = 73.4,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "A necromantic academy beneath Caer Darrow where the Cult of the Damned trains under Darkmaster Gandling.",
                descriptionUk = "Некромантична академія під Каер Дарроу, де Культ Проклятих навчається під керівництвом Темного магістра Ґандлінґа.",
                bossCount = 14,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },
        },

        Forever = {
            hall_of_thanes = {
                name = "Hall of Thanes",
                aliases = { "The Hall of Thanes" },
                isForeverNew = true,
                levelMin = 13,
                levelMax = 18,
                minEntryLevel = nil,
                zone = "Ironforge",
                parentZone = "Dun Morogh",
                x = 43.0,
                y = 51.0,
                players = nil,
                maxPlayers = nil,
                coordStatus = "verified",
                coordSource = "wowhead",
                note = "Inside Ironforge, in the High Seat / throne hall.",
                description = "Sacred dwarven burial chambers beneath Ironforge disturbed by Dark Iron intruders, restless dead, and other threats.",
                descriptionUk = "Священні поховальні зали дворфів під Стальгорном, потривожені вторгненням Чорного Заліза, неспокійною нежиттю та іншими загрозами.",
                bossCount = 4,
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            ruins_of_lordaeron = {
                name = "Ruins of Lordaeron",
                isForeverNew = true,
                levelMin = 15,
                levelMax = 20,
                minEntryLevel = nil,
                zone = "Tirisfal Glades",
                x = 61.3,
                y = 58.8,
                players = nil,
                maxPlayers = nil,
                coordStatus = "verified",
                coordSource = "dving",
                note = "Inner courtyard of the Lordaeron ruins above Undercity; approach through the former Lordaeron main gate.",
                description = "The shattered capital above Undercity has become a dungeon through ruined streets, Scourge remnants, and a necromancer's forces.",
                descriptionUk = "Зруйнована столиця над Підмістом стала підземеллям серед розбитих вулиць, залишків Плеті та сил некроманта.",
                bossCount = 7,
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            excavation_site_wetlands = {
                name = "Excavation Site: Wetlands",
                aliases = { "Excavation Site" },
                isForeverNew = true,
                levelMin = 24,
                levelMax = 29,
                minEntryLevel = nil,
                zone = "Wetlands",
                x = 36.8,
                y = 48.2,
                players = nil,
                maxPlayers = nil,
                coordStatus = "verified",
                coordSource = "wowgg_dving",
                note = "Dungeon entrance at Whelgar's Excavation Site in Wetlands.",
                description = "A dwarven excavation in the Wetlands has uncovered something ancient and dangerous beneath the dig site.",
                descriptionUk = "Дворфійські розкопки в Болотяних угіддях пробудили щось давнє й небезпечне під місцем експедиції.",
                bossCount = 4,
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            city_of_dalaran = {
                name = "City of Dalaran",
                isForeverNew = true,
                levelMin = 28,
                levelMax = 33,
                minEntryLevel = nil,
                zone = "Alterac Mountains",
                x = 32.4,
                y = 66.7,
                players = nil,
                maxPlayers = nil,
                coordStatus = "verified",
                coordSource = "wowgg_dving",
                note = "Entrance beneath the Violet Dome of Dalaran.",
                description = "The ruined magical city lies under an unstable arcane dome, with magical disturbances and demonic influence spreading through its streets.",
                descriptionUk = "Зруйноване магічне місто перебуває під нестабільним арканним куполом, а його вулицями ширяться магічні аномалії та демонічний вплив.",
                bossCount = 9,
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            drowned_city = {
                name = "The Drowned City",
                aliases = { "Drowned City" },
                isForeverNew = true,
                levelMin = 35,
                levelMax = 40,
                minEntryLevel = nil,
                zone = "Stranglethorn Vale",
                x = 19.8,
                y = 22.4,
                players = nil,
                maxPlayers = nil,
                coordStatus = "verified",
                coordSource = "wowgg_dving",
                note = "Underwater entrance near the north-west coast; dive toward the ruined troll columns. Level range 35-40 uses the corrected Forever table.",
                description = "A sunken troll city has risen along Stranglethorn's coast, now occupied by naga, risen trolls, makrura, and dangers in its flooded depths.",
                descriptionUk = "Затонуле трольське місто піднялося біля узбережжя Тернистої долини; тепер його населяють наги, повсталі тролі, макрури та небезпеки затоплених глибин.",
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            kroldok_stronghold = {
                name = "Krol'Dok Stronghold",
                aliases = { "Krol’dok Stronghold", "Krol'Dok" },
                isForeverNew = true,
                levelMin = 40,
                levelMax = 45,
                minEntryLevel = nil,
                zone = "The Riverglades",
                aliasesZones = { "Riverglades" },
                x = 74.2,
                y = 33.5,
                players = nil,
                maxPlayers = nil,
                coordStatus = "verified",
                coordSource = "wowgg_dving_wowhead",
                note = "Stronghold in the wooded eastern ravine. Level range 40-45 is the corrected Blizzard-published range.",
                description = "A new stronghold dungeon in the Riverglades frontier, built around the dangers occupying the region's eastern reaches.",
                descriptionUk = "Нове підземелля-фортеця на рубежах Ріверґлейдс, пов'язане із загрозами східної частини регіону.",
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            alcaz_prison = {
                name = "Alcaz Prison",
                aliases = { "Alcaz Island Prison" },
                isForeverNew = true,
                levelMin = 48,
                levelMax = 53,
                minEntryLevel = nil,
                zone = "Dustwallow Marsh",
                x = 78.4,
                y = 18.2,
                players = nil,
                maxPlayers = nil,
                coordStatus = "verified",
                coordSource = "wowgg_dving_wowhead",
                note = "Entrance on Alcaz Island, leading into the prison complex beneath the main fort.",
                description = "A prison complex on Alcaz Island beneath the main fort, opening a new high-level expedition off Dustwallow Marsh.",
                descriptionUk = "Тюремний комплекс на острові Алькац під головною фортецею, що відкриває нову високорівневу експедицію біля Пилових боліт.",
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            blackmaw_hold = {
                name = "Blackmaw Hold",
                isForeverNew = true,
                levelMin = 55,
                levelMax = 60,
                minEntryLevel = nil,
                zone = "Azshara",
                x = 23.4,
                y = 28.5,
                players = nil,
                maxPlayers = nil,
                coordStatus = "verified",
                coordSource = "wowgg_dving_wowhead",
                note = "Far north of Azshara, behind the large furbolg gate. The dungeon also connects onward toward Barrow Deeps.",
                description = "A high-level dungeon in northern Azshara centered on corruption stirring within the furbolg hold and its depths.",
                descriptionUk = "Високорівневе підземелля на півночі Азшари, де в глибинах фортеці фурболґів шириться тривожне осквернення.",
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            shapers_terrace = {
                name = "Shaper's Terrace",
                aliases = { "The Shaper's Terrace", "Shaper’s Terrace" },
                isForeverNew = true,
                levelMin = 58,
                levelMax = 60,
                minEntryLevel = nil,
                zone = "Un'Goro Crater",
                x = 41.6,
                y = 11.2,
                players = nil,
                maxPlayers = nil,
                coordStatus = "verified",
                coordSource = "wowgg_dving",
                note = "High on the rocky slopes along the northern wall of Un'Goro Crater.",
                description = "A high-level expedition into Titan mysteries on the northern heights of Un'Goro Crater.",
                descriptionUk = "Високорівнева експедиція до таємниць титанів на північних висотах кратера Ун'Ґоро.",
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },
        },
    },

    Raids = {
        Classic = {
            molten_core = {
                name = "Molten Core",
                aliases = { "MC" },
                levelMin = 60,
                levelMax = 60,
                zone = "Burning Steppes",
                location = "Blackrock Mountain",
                x = 26.3,
                y = 24.6,
                players = 40,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "Ragnaros and his lieutenants command the fiery heart of Blackrock Mountain; in Forever, Molten Core follows the opening raid tier instead of starting it.",
                descriptionUk = "Раґнарос і його слуги панують у вогняному серці Чорної гори; у Forever Вогняні Надра йдуть після стартового рейдового тиру, а не відкривають його.",
                bossCount = 10,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
                foreverChange = "Forever changes the raid progression order: Molten Core comes after the opening tier rather than opening level-60 raiding.",
                foreverChangeUk = "Forever змінює порядок рейдової прогресії: Вогняні Надра йдуть після стартового тиру, а не відкривають рейдинг 60 рівня.",
            },

            onyxias_lair = {
                name = "Onyxia's Lair",
                aliases = { "Onyxia", "Ony" },
                levelMin = 60,
                levelMax = 60,
                zone = "Dustwallow Marsh",
                x = 52.3,
                y = 76.1,
                players = 40,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "Onyxia's one-boss lair in Dustwallow Marsh returns as the 40-player raid of Forever's opening tier alongside 10- and 20-player raids.",
                descriptionUk = "Однобосове лігво Оніксії в Пилових болотах повертається як 40-гравцевий рейд стартового тиру Forever поруч із рейдами на 10 і 20 гравців.",
                bossCount = 1,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
                foreverChange = "Onyxia's Lair is moved into Forever's opening raid tier, unlocking with Barrow Deeps and Hyjal Summit on December 9, 2026.",
                foreverChangeUk = "Лігво Оніксії перенесене до стартового рейдового тиру Forever і відкривається разом із Barrow Deeps та Hyjal Summit 9 грудня 2026 року.",
                bosses = { "Onyxia" },
            },

            blackwing_lair = {
                name = "Blackwing Lair",
                aliases = { "BWL" },
                levelMin = 60,
                levelMax = 60,
                zone = "Burning Steppes",
                location = "Blackrock Mountain",
                x = 32.5,
                y = 32.4,
                players = 40,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "Nefarian's laboratory atop Blackrock Mountain, where the black dragonflight experiments on other dragonflights to create a chromatic brood.",
                descriptionUk = "Лабораторія Нефаріана на вершині Чорної гори, де чорні дракони експериментують над іншими зграями, створюючи хроматичний виводок.",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "returning",
            },

            zulgurub = {
                name = "Zul'Gurub",
                aliases = { "ZG" },
                levelMin = 60,
                levelMax = 60,
                zone = "Stranglethorn Vale",
                x = 54.0,
                y = 17.6,
                players = 20,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "A 20-player assault on the Gurubashi capital where Hakkar's priests prepare the Soulflayer's return.",
                descriptionUk = "20-гравцевий похід у столицю Ґурубаші, де жерці Гаккара готують повернення Пожирача Душ.",
                bossCount = 10,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "returning",
            },

            ruins_of_ahnqiraj = {
                name = "Ruins of Ahn'Qiraj",
                aliases = { "AQ20" },
                levelMin = 60,
                levelMax = 60,
                zone = "Silithus",
                x = 29.0,
                y = 92.8,
                players = 20,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "The outer city of the qiraji empire beyond the Scarab Wall, defended by field armies and six raid encounters.",
                descriptionUk = "Зовнішнє місто імперії кіраджів за Скарабеєвою Стіною, яке захищають польові армії та шість рейдових зустрічей.",
                bossCount = 6,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "returning",
            },

            temple_of_ahnqiraj = {
                name = "Temple of Ahn'Qiraj",
                aliases = { "AQ40" },
                levelMin = 60,
                levelMax = 60,
                zone = "Silithus",
                x = 29.0,
                y = 92.7,
                players = 40,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                description = "A descent into the heart of the qiraji empire and the prison of the Old God C'Thun.",
                descriptionUk = "Спуск у саме серце імперії кіраджів і до в'язниці Старого Бога К'Туна.",
                bossCount = 9,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "returning",
            },

            naxxramas = {
                name = "Naxxramas",
                aliases = { "Naxx" },
                levelMin = 60,
                levelMax = 60,
                zone = "Eastern Plaguelands",
                x = 39.0,
                y = 26.0,
                players = 40,
                coordStatus = "cross_checked",
                coordSource = "wowhead_classic",
                note = "Ground entry is the Plaguewood teleport spire; the necropolis itself floats above the zone.",
                description = "Kel'Thuzad's floating necropolis above the Eastern Plaguelands, with four wings and fifteen encounters leading to the lich himself.",
                descriptionUk = "Летючий некрополь Кел'Тузада над Східними Чумними землями: чотири крила й п'ятнадцять зустрічей, що ведуть до самого ліча.",
                bossCount = 15,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "returning",
            },
        },

        Forever = {
            barrow_deeps = {
                name = "Barrow Deeps",
                aliases = { "The Barrow Deeps" },
                isForeverNew = true,
                levelMin = 60,
                levelMax = 60,
                zone = "Mount Hyjal",
                x = nil,
                y = nil,
                players = 10,
                coordStatus = "tba",
                note = "Warcraft Tavern identifies a Mount Hyjal entrance and says two other entrances are still TBA.",
                description = "A new 10-player raid beneath Mount Hyjal, where ancient barrow dens and the Emerald Dream have become the focus of a dangerous disturbance.",
                descriptionUk = "Новий 10-гравцевий рейд під горою Гіджал, де стародавні курганні сховища й Смарагдовий Сон стали осередком небезпечного порушення.",
                bossCount = 8,
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
                bosses = { "Deepscar Matriarch", "Elder Tangleclaw", "Khalith the Dreadspinner", "Well of Sorrow", "Amethrax", "Del'lynar Songwood", "Ravus and Darlyssa", "Sonya Darkhallow" },
            },

            hyjal_summit = {
                name = "Hyjal Summit",
                isForeverNew = true,
                levelMin = 60,
                levelMax = 60,
                zone = "Mount Hyjal",
                x = nil,
                y = nil,
                players = 20,
                coordStatus = "tba",
                note = "Location is confirmed as Mount Hyjal; a reliable entrance coordinate is not yet published in the checked sources.",
                description = "A new 20-player raid atop Mount Hyjal, returning to sacred ground around Nordrassil where a new threat is stirring after the Third War.",
                descriptionUk = "Новий 20-гравцевий рейд на вершині Гіджалу — священній землі біля Нордрассілу, де після Третьої війни пробуджується нова загроза.",
                bossCount = 13,
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
                bosses = { "Bandalar", "Ancient of Decay", "Time-lost Battalion", "Sylvestris Dusksong", "Old Gloomlurker", "Gharalis the Abyssal", "Kathris the Haunted", "Anara Chillwind", "Elder Minderel", "Tracker Stillwind", "Council of Thorns", "Nythus the Dreambound", "The Wild King" },
            },
        },
    },
}

-- Convert percentage coordinates (e.g. 53.0, 48.9) to normalized 0..1.
function DB.GetNormalizedCoordinates(instance)
    if not instance or type(instance.x) ~= "number" or type(instance.y) ~= "number" then
        return nil, nil
    end

    return instance.x / 100, instance.y / 100
end

-- Inclusive level-range helper.
function DB.IsInLevelRange(instance, level)
    if not instance or type(level) ~= "number" then
        return false
    end

    return level >= instance.levelMin and level <= instance.levelMax
end

-- Returns Classic + Forever dungeon records without mutating the source tables.
function DB.GetAllDungeons()
    local result = {}

    for id, data in pairs(DB.Dungeons.Classic) do
        result[id] = data
    end

    for id, data in pairs(DB.Dungeons.Forever) do
        result[id] = data
    end

    return result
end

-- Returns Classic + Forever raid records without mutating the source tables.
function DB.GetAllRaids()
    local result = {}

    for id, data in pairs(DB.Raids.Classic) do
        result[id] = data
    end

    for id, data in pairs(DB.Raids.Forever) do
        result[id] = data
    end

    return result
end

ns.DB = DB
