-- Forever Instances - WoW Forever only
-- Data source: user-provided WoWForeverInstances.lua
local addonName, ns = ...

-- WoWForeverInstances.lua
-- Consolidated WoW Forever dungeon / raid database.
--
-- Primary sources:
--   https://www.warcrafttavern.com/forever/guides/dungeons/
--   https://wowhandbook.com/zones/dungeons/
--   https://www.warcrafttavern.com/forever/guides/raids/
--   https://wowhandbook.com/zones/raids/
--
-- Coordinates are zone-map percentages (0..100), NOT normalized 0..1.
-- Use DB.GetNormalizedCoordinates() for C_Map / normalized consumers.
--
-- Data policy:
--   * Level ranges: current WoW Forever table from Warcraft Tavern.
--   * Classic entrance coords: WoW Handbook where consistent.
--   * Conflicting coordinates were cross-checked instead of copied blindly.
--   * Unknown/TBA Forever entrance coordinates remain nil.
--   * Unified descriptions: concise paraphrases synthesized from the checked Forever dungeon/raid resources;
--     the UI does not split descriptions by source.
--   * Returning Classic instances are marked as available in Forever without duplicating map nodes.
--   * Unnamed roadmap raids are intentionally not added as map records until a name/location is published.
--   * Dungeon territory is normalized as Alliance / Horde / Contested for tooltip faction context.

local DB = {
    version = 3,
    coordinateUnit = "percent",

    Dungeons = {
        Classic = {
            ragefire_chasm = {
                name = "Ragefire Chasm",
                levelMin = 13,
                levelMax = 18,
                minEntryLevel = 8,
                zone = "Orgrimmar",
                territory = "Horde",
                x = 53.0,
                y = 48.9,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_RAGEFIRE_CHASM_DESCRIPTION",
                bossCount = 4,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            deadmines = {
                name = "The Deadmines",
                aliases = { "Deadmines" },
                levelMin = 15,
                levelMax = 22,
                minEntryLevel = 10,
                zone = "Westfall",
                territory = "Alliance",
                x = 38.2,
                y = 77.5,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_DEADMINES_DESCRIPTION",
                bossCount = 7,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            wailing_caverns = {
                name = "Wailing Caverns",
                levelMin = 17,
                levelMax = 24,
                minEntryLevel = 10,
                zone = "The Barrens",
                territory = "Horde",
                x = 46.0,
                y = 36.3,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_WAILING_CAVERNS_DESCRIPTION",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            shadowfang_keep = {
                name = "Shadowfang Keep",
                levelMin = 20,
                levelMax = 26,
                minEntryLevel = 10,
                zone = "Silverpine Forest",
                territory = "Horde",
                x = 44.7,
                y = 67.8,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_SHADOWFANG_KEEP_DESCRIPTION",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            blackfathom_deeps = {
                name = "Blackfathom Deeps",
                aliases = { "BFD" },
                levelMin = 22,
                levelMax = 28,
                minEntryLevel = 10,
                zone = "Ashenvale",
                territory = "Contested",
                x = 14.5,
                y = 14.6,
                players = 5,
                maxPlayers = 10,
                coordStatus = "conflict_resolved",
                coordSource = "warcrafttavern",
                noteKey = "INSTANCE_BLACKFATHOM_DEEPS_NOTE",
                descriptionKey = "INSTANCE_BLACKFATHOM_DEEPS_DESCRIPTION",
                bossCount = 7,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            the_stockade = {
                name = "The Stockade",
                aliases = { "Stockade", "The Stockades" },
                levelMin = 25,
                levelMax = 29,
                minEntryLevel = 15,
                zone = "Stormwind City",
                territory = "Alliance",
                x = 50.4,
                y = 66.2,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_THE_STOCKADE_DESCRIPTION",
                bossCount = 5,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            gnomeregan = {
                name = "Gnomeregan",
                levelMin = 29,
                levelMax = 38,
                minEntryLevel = 15,
                zone = "Dun Morogh",
                territory = "Alliance",
                x = 24.0,
                y = 40.0,
                players = 5,
                maxPlayers = 10,
                coordStatus = "cross_checked",
                coordSource = "warcrafttavern",
                noteKey = "INSTANCE_GNOMEREGAN_NOTE",
                descriptionKey = "INSTANCE_GNOMEREGAN_DESCRIPTION",
                bossCount = 5,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            razorfen_kraul = {
                name = "Razorfen Kraul",
                aliases = { "RFK" },
                levelMin = 29,
                levelMax = 38,
                minEntryLevel = 15,
                zone = "The Barrens",
                territory = "Horde",
                x = 42.3,
                y = 89.9,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_RAZORFEN_KRAUL_DESCRIPTION",
                bossCount = 6,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            scarlet_monastery = {
                name = "The Scarlet Monastery",
                aliases = { "Scarlet Monastery", "SM" },
                levelMin = 30,
                levelMax = 46,
                minEntryLevel = 20,
                zone = "Tirisfal Glades",
                territory = "Horde",
                x = 85.1,
                y = 31.4,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                wings = {
                    graveyard = {
                        name = "Graveyard",
                        fullName = "The Scarlet Monastery - Graveyard",
                        levelMin = 30,
                        levelMax = 38,
                        minEntryLevel = 20,
                        players = 5,
                        maxPlayers = 10,
                    },
                    library = {
                        name = "Library",
                        fullName = "The Scarlet Monastery - Library",
                        levelMin = 33,
                        levelMax = 41,
                        minEntryLevel = 20,
                        players = 5,
                        maxPlayers = 10,
                    },
                    armory = {
                        name = "Armory",
                        fullName = "The Scarlet Monastery - Armory",
                        levelMin = 36,
                        levelMax = 44,
                        minEntryLevel = 20,
                        players = 5,
                        maxPlayers = 10,
                    },
                    cathedral = {
                        name = "Cathedral",
                        fullName = "The Scarlet Monastery - Cathedral",
                        levelMin = 38,
                        levelMax = 46,
                        minEntryLevel = 20,
                        players = 5,
                        maxPlayers = 10,
                    },
                },
                descriptionKey = "INSTANCE_SCARLET_MONASTERY_DESCRIPTION",
                bossCount = 7,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            uldaman = {
                name = "Uldaman",
                levelMin = 36,
                levelMax = 45,
                minEntryLevel = 30,
                zone = "Badlands",
                territory = "Contested",
                x = 44.2,
                y = 12.2,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_ULDAMAN_DESCRIPTION",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            razorfen_downs = {
                name = "Razorfen Downs",
                aliases = { "RFD" },
                levelMin = 37,
                levelMax = 46,
                minEntryLevel = 25,
                zone = "The Barrens",
                territory = "Horde",
                x = 50.9,
                y = 92.9,
                players = 5,
                maxPlayers = 10,
                coordStatus = "cross_checked",
                coordSource = "wowhandbook",
                noteKey = "INSTANCE_RAZORFEN_DOWNS_NOTE",
                descriptionKey = "INSTANCE_RAZORFEN_DOWNS_DESCRIPTION",
                bossCount = 6,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            zulfarrak = {
                name = "Zul'Farrak",
                aliases = { "ZF" },
                levelMin = 40,
                levelMax = 47,
                minEntryLevel = 35,
                zone = "Tanaris",
                territory = "Contested",
                x = 38.7,
                y = 19.9,
                players = 5,
                maxPlayers = 10,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_ZULFARRAK_DESCRIPTION",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            maraudon = {
                name = "Maraudon",
                levelMin = 45,
                levelMax = 51,
                minEntryLevel = 30,
                zone = "Desolace",
                territory = "Contested",
                x = 29.3,
                y = 62.5,
                players = 5,
                maxPlayers = 10,
                coordStatus = "cross_checked",
                coordSource = "wowhandbook",
                approach = {
                    x = 38.0,
                    y = 58.0,
                    label = "Valley of Spears / exterior approach",
                    source = "warcrafttavern",
                },
                descriptionKey = "INSTANCE_MARAUDON_DESCRIPTION",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            temple_of_atal_hakkar = {
                name = "The Temple of Atal'Hakkar",
                aliases = { "Temple of Atal'Hakkar", "Sunken Temple", "ST" },
                levelMin = 50,
                levelMax = 55,
                minEntryLevel = 35,
                zone = "Swamp of Sorrows",
                territory = "Contested",
                x = 69.0,
                y = 54.0,
                players = 5,
                maxPlayers = 10,
                coordStatus = "conflict_resolved",
                coordSource = "cross_check",
                noteKey = "INSTANCE_TEMPLE_OF_ATAL_HAKKAR_NOTE",
                descriptionKey = "INSTANCE_TEMPLE_OF_ATAL_HAKKAR_DESCRIPTION",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            blackrock_depths = {
                name = "Blackrock Depths",
                aliases = { "BRD" },
                levelMin = 52,
                levelMax = 60,
                minEntryLevel = 40,
                location = "Blackrock Mountain",
                zone = "Searing Gorge",
                territory = "Contested",
                x = 27.1,
                y = 72.5,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_BLACKROCK_DEPTHS_DESCRIPTION",
                bossCount = 21,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            blackrock_spire = {
                name = "Blackrock Spire",
                aliases = { "BRS" },
                levelMin = 57,
                levelMax = 60,
                minEntryLevel = 45,
                location = "Blackrock Mountain",
                zone = "Burning Steppes",
                territory = "Contested",
                players = 5,
                maxPlayers = 10,
                x = 33.0,
                y = 25.2,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                wings = {
                    lower = {
                        name = "Lower Blackrock Spire",
                        aliases = { "LBRS" },
                        levelMin = 57,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 5,
                        maxPlayers = 10,
                    },
                    upper = {
                        name = "Upper Blackrock Spire",
                        aliases = { "UBRS" },
                        levelMin = 60,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 10,
                        maxPlayers = 10,
                    },
                },
                descriptionKey = "INSTANCE_BLACKROCK_SPIRE_DESCRIPTION",
                bossCount = 14,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            dire_maul = {
                name = "Dire Maul",
                aliases = { "DM" },
                levelMin = 58,
                levelMax = 60,
                minEntryLevel = 45,
                zone = "Feralas",
                territory = "Contested",
                players = 5,
                maxPlayers = 5,
                x = 62.0,
                y = 33.3,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                wings = {
                    east = {
                        name = "Dire Maul East",
                        aliases = { "DME" },
                        levelMin = 58,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 5,
                        maxPlayers = 5,
                    },
                    west = {
                        name = "Dire Maul West",
                        aliases = { "DMW" },
                        levelMin = 60,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 5,
                        maxPlayers = 5,
                    },
                    north = {
                        name = "Dire Maul North",
                        aliases = { "DMN" },
                        levelMin = 60,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 5,
                        maxPlayers = 5,
                    },
                },
                descriptionKey = "INSTANCE_DIRE_MAUL_DESCRIPTION",
                bossCount = 19,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            stratholme = {
                name = "Stratholme",
                levelMin = 58,
                levelMax = 60,
                minEntryLevel = 45,
                zone = "Eastern Plaguelands",
                territory = "Contested",
                x = 26.1,
                y = 10.4,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                wings = {
                    living = {
                        name = "Stratholme - Living",
                        aliases = { "Stratholme: Live", "Strat Live" },
                        levelMin = 58,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 5,
                        maxPlayers = 5,
                    },
                    undead = {
                        name = "Stratholme - Undead",
                        aliases = { "Stratholme: Dead", "Strat UD" },
                        levelMin = 58,
                        levelMax = 60,
                        minEntryLevel = 45,
                        players = 5,
                        maxPlayers = 5,
                    },
                },
                descriptionKey = "INSTANCE_STRATHOLME_DESCRIPTION",
                bossCount = 19,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },

            scholomance = {
                name = "Scholomance",
                aliases = { "Scholo" },
                levelMin = 58,
                levelMax = 60,
                minEntryLevel = 45,
                zone = "Western Plaguelands",
                territory = "Contested",
                x = 69.7,
                y = 73.4,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_SCHOLOMANCE_DESCRIPTION",
                bossCount = 14,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
            },
        },

        Forever = {
            hall_of_thanes = {
                name = "Hall of Thanes",
                aliases = { "The Hall of Thanes" },
                isForeverNew = true,
                levelMin = 13,
                levelMax = 18,
                minEntryLevel = nil,
                zone = "Ironforge",
                territory = "Alliance",
                parentZone = "Dun Morogh",
                x = 43.0,
                y = 51.0,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowhead",
                noteKey = "INSTANCE_HALL_OF_THANES_NOTE",
                descriptionKey = "INSTANCE_HALL_OF_THANES_DESCRIPTION",
                bossCount = 4,
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            ruins_of_lordaeron = {
                name = "Ruins of Lordaeron",
                isForeverNew = true,
                levelMin = 15,
                levelMax = 20,
                minEntryLevel = nil,
                zone = "Tirisfal Glades",
                territory = "Horde",
                x = 61.3,
                y = 58.8,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "dving",
                noteKey = "INSTANCE_RUINS_OF_LORDAERON_NOTE",
                descriptionKey = "INSTANCE_RUINS_OF_LORDAERON_DESCRIPTION",
                bossCount = 7,
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            excavation_site_wetlands = {
                name = "Excavation Site: Wetlands",
                aliases = { "Excavation Site" },
                isForeverNew = true,
                levelMin = 24,
                levelMax = 29,
                minEntryLevel = nil,
                zone = "Wetlands",
                territory = "Contested",
                x = 36.8,
                y = 48.2,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowgg_dving",
                noteKey = "INSTANCE_EXCAVATION_SITE_WETLANDS_NOTE",
                descriptionKey = "INSTANCE_EXCAVATION_SITE_WETLANDS_DESCRIPTION",
                bossCount = 4,
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            city_of_dalaran = {
                name = "City of Dalaran",
                isForeverNew = true,
                levelMin = 28,
                levelMax = 33,
                minEntryLevel = nil,
                zone = "Alterac Mountains",
                territory = "Contested",
                x = 32.4,
                y = 66.7,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowgg_dving",
                noteKey = "INSTANCE_CITY_OF_DALARAN_NOTE",
                descriptionKey = "INSTANCE_CITY_OF_DALARAN_DESCRIPTION",
                bossCount = 9,
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            drowned_city = {
                name = "The Drowned City",
                aliases = { "Drowned City" },
                isForeverNew = true,
                levelMin = 35,
                levelMax = 40,
                minEntryLevel = nil,
                zone = "Stranglethorn Vale",
                territory = "Contested",
                x = 19.8,
                y = 22.4,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowgg_dving",
                noteKey = "INSTANCE_DROWNED_CITY_NOTE",
                descriptionKey = "INSTANCE_DROWNED_CITY_DESCRIPTION",
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            kroldok_stronghold = {
                name = "Krol'Dok Stronghold",
                aliases = { "Krol’dok Stronghold", "Krol'Dok" },
                isForeverNew = true,
                levelMin = 40,
                levelMax = 45,
                minEntryLevel = nil,
                zone = "The Riverglades",
                territory = "Contested",
                aliasesZones = { "Riverglades" },
                x = 74.2,
                y = 33.5,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowgg_dving_wowhead",
                noteKey = "INSTANCE_KROLDOK_STRONGHOLD_NOTE",
                descriptionKey = "INSTANCE_KROLDOK_STRONGHOLD_DESCRIPTION",
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            alcaz_prison = {
                name = "Alcaz Prison",
                aliases = { "Alcaz Island Prison" },
                isForeverNew = true,
                levelMin = 48,
                levelMax = 53,
                minEntryLevel = nil,
                zone = "Dustwallow Marsh",
                territory = "Contested",
                x = 78.4,
                y = 18.2,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowgg_dving_wowhead",
                noteKey = "INSTANCE_ALCAZ_PRISON_NOTE",
                descriptionKey = "INSTANCE_ALCAZ_PRISON_DESCRIPTION",
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            blackmaw_hold = {
                name = "Blackmaw Hold",
                isForeverNew = true,
                levelMin = 55,
                levelMax = 60,
                minEntryLevel = nil,
                zone = "Azshara",
                territory = "Contested",
                x = 23.4,
                y = 28.5,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowgg_dving_wowhead",
                noteKey = "INSTANCE_BLACKMAW_HOLD_NOTE",
                descriptionKey = "INSTANCE_BLACKMAW_HOLD_DESCRIPTION",
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },

            shapers_terrace = {
                name = "Shaper's Terrace",
                aliases = { "The Shaper's Terrace", "Shaper’s Terrace" },
                isForeverNew = true,
                levelMin = 58,
                levelMax = 60,
                minEntryLevel = nil,
                zone = "Un'Goro Crater",
                territory = "Contested",
                x = 41.6,
                y = 11.2,
                players = 5,
                maxPlayers = 5,
                coordStatus = "verified",
                coordSource = "wowgg_dving",
                noteKey = "INSTANCE_SHAPERS_TERRACE_NOTE",
                descriptionKey = "INSTANCE_SHAPERS_TERRACE_DESCRIPTION",
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
            },
        },
    },

    Raids = {
        Classic = {
            molten_core = {
                name = "Molten Core",
                aliases = { "MC" },
                levelMin = 60,
                levelMax = 60,
                zone = "Burning Steppes",
                location = "Blackrock Mountain",
                x = 26.3,
                y = 24.6,
                players = 40,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_MOLTEN_CORE_DESCRIPTION",
                bossCount = 10,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
                foreverChangeKey = "INSTANCE_MOLTEN_CORE_FOREVER_CHANGE",
            },

            onyxias_lair = {
                name = "Onyxia's Lair",
                aliases = { "Onyxia", "Ony" },
                levelMin = 60,
                levelMax = 60,
                zone = "Dustwallow Marsh",
                x = 52.3,
                y = 76.1,
                players = 40,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_ONYXIAS_LAIR_DESCRIPTION",
                bossCount = 1,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "updated",
                foreverChangeKey = "INSTANCE_ONYXIAS_LAIR_FOREVER_CHANGE",
                bosses = { "Onyxia" },
            },

            blackwing_lair = {
                name = "Blackwing Lair",
                aliases = { "BWL" },
                levelMin = 60,
                levelMax = 60,
                zone = "Burning Steppes",
                location = "Blackrock Mountain",
                x = 32.5,
                y = 32.4,
                players = 40,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_BLACKWING_LAIR_DESCRIPTION",
                bossCount = 8,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "returning",
            },

            zulgurub = {
                name = "Zul'Gurub",
                aliases = { "ZG" },
                levelMin = 60,
                levelMax = 60,
                zone = "Stranglethorn Vale",
                x = 54.0,
                y = 17.6,
                players = 20,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_ZULGURUB_DESCRIPTION",
                bossCount = 10,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "returning",
            },

            ruins_of_ahnqiraj = {
                name = "Ruins of Ahn'Qiraj",
                aliases = { "AQ20" },
                levelMin = 60,
                levelMax = 60,
                zone = "Silithus",
                x = 29.0,
                y = 92.8,
                players = 20,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_RUINS_OF_AHNQIRAJ_DESCRIPTION",
                bossCount = 6,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "returning",
            },

            temple_of_ahnqiraj = {
                name = "Temple of Ahn'Qiraj",
                aliases = { "AQ40" },
                levelMin = 60,
                levelMax = 60,
                zone = "Silithus",
                x = 29.0,
                y = 92.7,
                players = 40,
                coordStatus = "verified",
                coordSource = "wowhandbook",
                descriptionKey = "INSTANCE_TEMPLE_OF_AHNQIRAJ_DESCRIPTION",
                bossCount = 9,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "returning",
            },

            naxxramas = {
                name = "Naxxramas",
                aliases = { "Naxx" },
                levelMin = 60,
                levelMax = 60,
                zone = "Eastern Plaguelands",
                x = 39.0,
                y = 26.0,
                players = 40,
                coordStatus = "cross_checked",
                coordSource = "wowhead_classic",
                noteKey = "INSTANCE_NAXXRAMAS_NOTE",
                descriptionKey = "INSTANCE_NAXXRAMAS_DESCRIPTION",
                bossCount = 15,
                origin = "Classic",
                availableInForever = true,
                foreverStatus = "returning",
            },
        },

        Forever = {
            barrow_deeps = {
                name = "Barrow Deeps",
                aliases = { "The Barrow Deeps" },
                isForeverNew = true,
                levelMin = 60,
                levelMax = 60,
                zone = "Mount Hyjal",
                x = nil,
                y = nil,
                players = 10,
                coordStatus = "tba",
                noteKey = "INSTANCE_BARROW_DEEPS_NOTE",
                descriptionKey = "INSTANCE_BARROW_DEEPS_DESCRIPTION",
                bossCount = 8,
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
                bosses = { "Deepscar Matriarch", "Elder Tangleclaw", "Khalith the Dreadspinner", "Well of Sorrow", "Amethrax", "Del'lynar Songwood", "Ravus and Darlyssa", "Sonya Darkhallow" },
            },

            hyjal_summit = {
                name = "Hyjal Summit",
                isForeverNew = true,
                levelMin = 60,
                levelMax = 60,
                zone = "Mount Hyjal",
                x = nil,
                y = nil,
                players = 20,
                coordStatus = "tba",
                noteKey = "INSTANCE_HYJAL_SUMMIT_NOTE",
                descriptionKey = "INSTANCE_HYJAL_SUMMIT_DESCRIPTION",
                bossCount = 13,
                origin = "Forever",
                availableInForever = true,
                foreverStatus = "new",
                bosses = { "Bandalar", "Ancient of Decay", "Time-lost Battalion", "Sylvestris Dusksong", "Old Gloomlurker", "Gharalis the Abyssal", "Kathris the Haunted", "Anara Chillwind", "Elder Minderel", "Tracker Stillwind", "Council of Thorns", "Nythus the Dreambound", "The Wild King" },
            },
        },
    },
}

-- Convert percentage coordinates (e.g. 53.0, 48.9) to normalized 0..1.
function DB.GetNormalizedCoordinates(instance)
    if not instance or type(instance.x) ~= "number" or type(instance.y) ~= "number" then
        return nil, nil
    end

    return instance.x / 100, instance.y / 100
end

-- Inclusive level-range helper.
function DB.IsInLevelRange(instance, level)
    if not instance or type(level) ~= "number" then
        return false
    end

    return level >= instance.levelMin and level <= instance.levelMax
end

-- Returns Classic + Forever dungeon records without mutating the source tables.
function DB.GetAllDungeons()
    local result = {}

    for id, data in pairs(DB.Dungeons.Classic) do
        result[id] = data
    end

    for id, data in pairs(DB.Dungeons.Forever) do
        result[id] = data
    end

    return result
end

-- Returns Classic + Forever raid records without mutating the source tables.
function DB.GetAllRaids()
    local result = {}

    for id, data in pairs(DB.Raids.Classic) do
        result[id] = data
    end

    for id, data in pairs(DB.Raids.Forever) do
        result[id] = data
    end

    return result
end

ns.DB = DB
